### ISSUE TITLE
Approx 50 email at once.

### ISSUE THREAD

**Issue by 1906sam** [crabstudio/emailqueue#2]
When I tried sending email to 600 users in one go, only 50 users successfully received emails. After that application stopped sending. Can you please help me here why is it so? I have tried multiple times and all those times application stopped after sending some emails.

**Comment by anhtuank7c** [comment]
@1906sam seem your template went wrong some where (IE: missing parameter to render).
Please post your details logs.

**Comment by 1906sam** [comment]
My template contains only images and I am not using any variables there. Here is my code for enqueue:

`$result = enqueue($userData, [
                'request' => $this->request
            ],
                [
                    'subject' => __('some text.'),
                    'format' => 'html',
                    'template' => 'welcome',
                    'layout' => 'welcome',
                    'config' => 'default',
                ],
                null,
                null,
                'abc@gmail.com'
            );`

**Comment by anhtuank7c** [comment]
@1906sam Do you have application logs?

**Comment by 1906sam** [comment]
yeah..I checked them also but there was nothing related to this.

**Comment by anhtuank7c** [comment]
This one will help you: https://github.com/crabstudio/emailqueue/blob/master/src/Shell/SenderShell.php#L32

**Comment by 1906sam** [comment]
great. Thanks !!
